name: e_commerce_app
description: A new Flutter for an E-Commerce App.
 
 
publish_to: 'none'   
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#-------------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http:
  intl:
  logger:
  url_launcher:
  flutter_native_splash:
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1


# Icons
  iconsax: 
  cupertino_icons: ^1.0.2

# State Management
  get: 
  get_storage:


# Product Specific




#------------- ./ PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter: 
  uses-material-design: true


  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/verify_email_images/
    - assets/icons/categories/



  #--------------- LOCAL ASSETS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800